### ISSUE TITLE
[whishlist] Samples on homepage

### ISSUE THREAD

**Issue by danialbehzadi** [jnaqsh/bootstrap#1]
I think it's a good idea to place "nerdnews.ir" as a sample in Persian home page of bootstrap

**Comment by hamedrnik** [comment]
Thanks, good idea.
In the next version, it will added too

**Comment by hamedrnik** [comment]
This is done by https://github.com/jnaqsh/bootstrap/commit/30f0342b430ef887cce71a4ca975bb3c7c67ac18
