### ISSUE TITLE
Typeahead render bug

### ISSUE THREAD

**Issue by saeedzareian** [jnaqsh/bootstrap#2]
Hi,

Thanks for your nice job,
There is a small issue, when a typeahead topdown menu appears. In chrome and android browser it floats to right side with a large width.

Please take a look ;)

Thanks and Happy Nowruz! ;)

**Comment by hamedrnik** [comment]
Hi,
Yes I know, but it's about js and i couldn't figure out but I try to fix it in the next version
Thanks for your report and Happy Nowrouz too! ;)

**Comment by saeedzareian** [comment]
I've searched the net, there is also another project of RTLing Bootstrap by @kiyarash Soleimanzadeh.

The project has not any link to download and It made me to use Visual Studio 2010 for a PHP website!
However I saw his source code and apparently he solved this issue before. He has done some calculations.
Please include this code in your code by replacing show method typeahead.

Thanks @kiyarash and @iCEAGE 

<code>
show: function () {
      var pos = $.extend({}, this.$element.position(), {
        height: this.$element[0].offsetHeight
      })
      // right position for RTL
      var right = ($(window).width() - (this.$element.offset().left + this.$element.outerWidth()));
      this.$menu
        .insertAfter(this.$element)
        .css({
          top: pos.top + pos.height
        , right: right
        })
        .show()
      this.shown = true
      return this
    }
</code>

**Comment by hamedrnik** [comment]
It's not working. I just set right position to 19px and all thing seem right.
By the way, thanks for your participating.
This is done by https://github.com/jnaqsh/bootstrap/commit/b8eb38198b7341a872665c3d026050f099309097

**Comment by KiarashS** [comment]
@iCEAGE It's not working!!! Are You Sure ?
it's working without any problem in Several projects.

again test that and enjoy!

**Comment by KiarashS** [comment]
It is reasonable set right position to 19px, which is a static value?

**Comment by hamedrnik** [comment]
Are you using rbootstrap? or using your customized bootstrap (https://github.com/kiyarash/RTL-Bootstrap)
I tested with rbootstrap.ir and your code doesn't work.

That is just monkey patch because i didn't find any solution to work. 19px is ok and it's work in 4 responsive of bootstrap.

**Comment by saeedzareian** [comment]
Of course a monkey patch will put us in trouble!

It think you didn't erase your cache @iCEAGE . Try with Ctrl+F5 again.
I've replaced @kiyarash function in your bootstrap.js and It works like a clock!

**Comment by KiarashS** [comment]
@iCEAGE No, i using my customized bootstrap, Of course that still not hosted in GitHub and hosted in NuGet.
css: https://nuget.org/packages/Twitter.Bootstrap.RTL
less: https://nuget.org/packages/Twitter.Bootstrap.RTL.Less

**Comment by KiarashS** [comment]
@saeedzareian thanks for test.

**Comment by hamedrnik** [comment]
I tested your code multiple of times and i didn't get any correct position.
Could you clone  https://github.com/jnaqsh/bootstrap repo and fix it and send a pull request?
![Screenshot from 2013-03-28 22:27:13](https://f.cloud.github.com/assets/217102/314678/5c3cadc6-97d1-11e2-99be-a11e3e52144a.png)

**Comment by hamedrnik** [comment]
@kiyarash @saeedzareian Your solution for making RTL typeahead is just worked when position css attribute sets to static (default) but it's not work when sets position to relative or fixed or absolute.
I found a better way as my monkey patching! and your solution. you can check it out https://github.com/jnaqsh/bootstrap/commit/aa1feb0914a63ff0319910401fac33e50a55c5c7
Now It works like a charm! :)
By the way, I appreciate your contributing to rbootstrap

**Comment by KiarashS** [comment]
@iCEAGE  thanks, i'm in travel, forgive me if I am late reply, i never tested that with another positions.
now i tested your solution and works, But thats better remove width and swap left and right.

anyway, thanks for better solution.

**Comment by hamedrnik** [comment]
@kiyarash How can i do that? position in JQuery is based on left and top and it's not depends on right and bottom and we have to calculate the right position with left attribute. for doing this, we have to calculate width of input and subtract width of menu.
Is there any better solution?

**Comment by KiarashS** [comment]
yes, do this:

``` javascript
   , show: function () {
       var pos = $.extend({}, this.$element.position(), {
        height: this.$element[0].offsetHeight
       })

       this.$menu
         .insertAfter(this.$element)
         .css({
           top: pos.top + pos.height
        , right: (pos.left + pos.width) - this.$menu.outerWidth()
        , left: "auto"
         })
         .show()
```

**Comment by hamedrnik** [comment]
When i set right: auto all things is going to be right. could you check it out this code:

```
 , show: function () {
    var pos = $.extend({}, this.$element.position(), {
     height: this.$element[0].offsetHeight
    })

    this.$menu
      .insertAfter(this.$element)
      .css({
        top: pos.top + pos.height
     , right: "auto"
      })
      .show()
```

**Comment by KiarashS** [comment]
@iCEAGE this approach doesn't work, i suggest use https://github.com/jnaqsh/bootstrap/issues/2#issuecomment-15709235

**Comment by hamedrnik** [comment]
I tested but your solution doesn't work in relative position https://github.com/jnaqsh/bootstrap/issues/2#issuecomment-15709235

**Comment by KiarashS** [comment]
i tested https://github.com/jnaqsh/bootstrap/issues/2#issuecomment-15709235 with relative position and works like a charm ;)
i set relative position to text input.
