### ISSUE TITLE
در مورد پروژه

### ISSUE THREAD

**Issue by mehdisadeghi** [jnaqsh/bootstrap#7]
چرا بجای ایجاد یک ریپوزیتوری جدید در خود پروژه بوت‌استرپ مشارکت نکردید مثلا تحت یک شاخه جدید؟ و اینکه چطور این پروژه رو با پروژه اصلی بروز نگه می‌دارید؟

**Comment by hamedrnik** [comment]
@mehdisadeghi دلیلش این بود که mfat و mdo قبول نکردند گرچه بعد از این‌که پروژه تموم شد، گفتند بیام و بر روی پروژه اصلی کار کنم که دیگه من زمانش رو نداشتم. بوت‌استرپ فارسی تا آخرین نسخهٔ ۲ منتشر شد. اما بعد از منتشر شدن نسخهٔ ۳ بوت‌استرپ، دیگر منتشر و به‌روز نشد.

**Comment by mehdisadeghi** [comment]
من این رو می‌بندم، چون جواب سوال رو گرفتم.
