### ISSUE TITLE
change style in accordian bootstrap

### ISSUE THREAD

**Issue by hhtuser** [jnaqsh/bootstrap#8]
I'm sorry I can not speak good English

I am using accordion bootstrap

I want to change the image and style when the menu pops up, like picture How do I do this?

باسلام 
من از منوی اکوردین بوت استرپ استفاده میکنم من میخوام وقتی منو باز میشه استایل و عکس ان تغییر کنه ایا بوت استرپ این امکان را دارا می باشد

**Comment by hamedrnik** [comment]
سلام
آره می‌تونید این کار رو انجام بدید. دستی این کار رو انجام بدید به بوت‌استرپ ارتباطی نداره
